# Generated by Django 3.1.7 on 2021-04-03 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='anuncios')),
            ],
            options={
                'verbose_name_plural': 'anuncios',
                'db_table': 'anuncio',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='AnuncioImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='anuncios')),
                ('fk_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.anuncio')),
            ],
            options={
                'verbose_name_plural': 'anuncios_imagens',
                'db_table': 'anuncio_imagem',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fk_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.categoria'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fk_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.status'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
