# Generated by Django 3.1.7 on 2021-04-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messagem',
            new_name='mensagem',
        ),
    ]
